name: Build WLED ESP32
on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Download official WLED 16_x
        run: |
          git clone -b 16_x https://github.com/wled/WLED.git src
          cd src

      - name: Compile pure WLED (esp32dev)
        run: |
          cd src
          pio run -e esp32dev

      - name: Save firmware
        working-directory: src
        uses: actions/upload-artifact@v4
        with:
          path: .pio/build/esp32dev/firmware.bin
          name: WLED_ESP32_Firmware
